### ISSUE TITLE
gpu_monitor.py文件中 class Process(Serialize): 的 to_json 函数报错

### ISSUE THREAD

**Issue by HuColin** [huww98/gpu-board-server#1]
```bash
[2019-10-11 01:55:24 +0000] [1] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2019-10-11 01:55:25 +0000] - (sanic.access)[INFO][192.168.1.50:35820]: GET http://192.168.1.52:8001/socket.io/?EIO=3&transport=polling&t=MsuXniE  200 119
[2019-10-11 01:55:25 +0000] - (sanic.access)[INFO][192.168.1.50:35820]: GET http://192.168.1.52:8001/socket.io/?EIO=3&transport=polling&t=MsuXniM&sid=4be54bf52d1b4869b386654f6d42df8d  200 4
Exception while retriving new status. fail in a row: 1
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 30, in update_gpu_stats
    gpu_stats = gm.to_json()
  File "/usr/src/app/gpu_monitor.py", line 175, in to_json
    'gpus': self.gpus.to_json(),
  File "/usr/src/app/gpu_monitor.py", line 154, in to_json
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 154, in <listcomp>
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 137, in to_json
    'processes': self.processes.to_json()
  File "/usr/src/app/gpu_monitor.py", line 107, in to_json
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 107, in <listcomp>
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 88, in to_json
    'name': self.name,
AttributeError: 'Process' object has no attribute 'name'
Exception while retriving new status. fail in a row: 2
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 30, in update_gpu_stats
    gpu_stats = gm.to_json()
  File "/usr/src/app/gpu_monitor.py", line 175, in to_json
    'gpus': self.gpus.to_json(),
  File "/usr/src/app/gpu_monitor.py", line 154, in to_json
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 154, in <listcomp>
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 137, in to_json
    'processes': self.processes.to_json()
  File "/usr/src/app/gpu_monitor.py", line 107, in to_json
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 107, in <listcomp>
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 88, in to_json
    'name': self.name,
AttributeError: 'Process' object has no attribute 'name'
Exception while retriving new status. fail in a row: 3
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 30, in update_gpu_stats
    gpu_stats = gm.to_json()
  File "/usr/src/app/gpu_monitor.py", line 175, in to_json
    'gpus': self.gpus.to_json(),
  File "/usr/src/app/gpu_monitor.py", line 154, in to_json
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 154, in <listcomp>
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 137, in to_json
    'processes': self.processes.to_json()
  File "/usr/src/app/gpu_monitor.py", line 107, in to_json
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 107, in <listcomp>
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 88, in to_json
    'name': self.name,
AttributeError: 'Process' object has no attribute 'name'
Exception while retriving new status. fail in a row: 4
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 30, in update_gpu_stats
    gpu_stats = gm.to_json()
  File "/usr/src/app/gpu_monitor.py", line 175, in to_json
    'gpus': self.gpus.to_json(),
  File "/usr/src/app/gpu_monitor.py", line 154, in to_json
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 154, in <listcomp>
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 137, in to_json
    'processes': self.processes.to_json()
  File "/usr/src/app/gpu_monitor.py", line 107, in to_json
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 107, in <listcomp>
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 88, in to_json
    'name': self.name,
AttributeError: 'Process' object has no attribute 'name'
Exception while retriving new status. fail in a row: 5
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 30, in update_gpu_stats
    gpu_stats = gm.to_json()
  File "/usr/src/app/gpu_monitor.py", line 175, in to_json
    'gpus': self.gpus.to_json(),
  File "/usr/src/app/gpu_monitor.py", line 154, in to_json
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 154, in <listcomp>
    return [gpu.to_json() for gpu in self.gpus]
  File "/usr/src/app/gpu_monitor.py", line 137, in to_json
    'processes': self.processes.to_json()
  File "/usr/src/app/gpu_monitor.py", line 107, in to_json
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 107, in <listcomp>
    return [process.to_json() for process in self.processes]
  File "/usr/src/app/gpu_monitor.py", line 88, in to_json
    'name': self.name,
AttributeError: 'Process' object has no attribute 'name'
Too many fail in a row, exiting
```
GPU: RTX 2080Ti
当时正在运行 darknet

**Comment by huww98** [comment]
在同样的配置上，曾经成功运行过吗？

这个错误显示程序未能找到GPU报告的正在运行的进程，我可以对这个错误进行一些防御，但正常情况下不应该经常出现这样的问题的吧。如使用Docker运行，请确保添加了`--pid host`参数

**Comment by HuColin** [comment]
> 在同样的配置上，曾经成功运行过吗？
> 
> 这个错误显示程序未能找到GPU报告的正在运行的进程，我可以对这个错误进行一些防御，但正常情况下不应该经常出现这样的问题的吧。如使用Docker运行，请确保添加了`--pid host`参数

重新试了一下，可以了
